### ISSUE TITLE
Suggestion: Change Stat Number

### ISSUE THREAD

**Issue by MajorCooke** [XaserAcheron/damnums#26]
I recommend allowing a settable stat number which people can change either in menu or by console, clamped anywhere from 70 to 90 (or 91-99).

- Mods may heavily rely upon thinker iterators. If the mod has the iterator set to a specific stat number, the mod has the best of interests in mind in not scanning every single thinker (including the built-in ones) while scanning for a particular type.
- Only applies to the numbers as well as the thinkers.

I can help on this if needed, should you decide to invest in this.

**Comment by XaserAcheron** [comment]
I'm following you somewhat -- now that we've got a dedicated range for mod statnums, it makes sense to explicitly use one. I'm not sure what you mean about allowing them to be changed by users, though; that's a really weird implementation detail to expose, and I'm not sure what the benefit is.

**Comment by MajorCooke** [comment]
Oh right, forgot to mention it'd be under an 'advanced' section with a warning that says "don't touch unless you know what you're doing"

Mainly for mods that have their own span of user_stats, like say someone mashes a mod with it and the mod super heavily relies upon one of the STAT_USER ones which just so happens to be the same as what this mod would use. For some mods, (and this is a bit of ridiculous example I know) 20 is not going to be enough.

Or you could take the risk and just do 126.

Ultimately I suppose it could just be left as a CVar alone with no menu entry.

**Comment by XaserAcheron** [comment]
What even happens if there's a stat number "conflict"? All I can think of is a potential impact on ThinkerIterator performance.

**Comment by MajorCooke** [comment]
Dunno. But I reckon it's something I might not want to find out especially if people don't do actual class checking on.

**Comment by XaserAcheron** [comment]
If a mod is using a ThinkerIterator without a class check and assumes everything on a particular stat number is a certain thing, that mod is doing something wrong. I'm not interested in adding workarounds for other mods' bugs -- best to fix that mod in such a case (which, fortunately, isn't that hard unless the modder is an absent or stubborn beastie).

**Comment by XaserAcheron** [comment]
Just assigned Statnum 88 across the board. Probably doesn't make much of a difference in the long run, but there you go. :P
